### ISSUE TITLE
tensorflow error

### ISSUE THREAD

**Issue by deevdevil88** [quon-titative-biology/scAlign#4]
Hello,
I have installed tensorflow and i know R locates it when i run py_config(), however everytime i try to run scAlign it gives me the error
Error in value[[3L]](cond) : 
  Error with system install of tensorflow, check R for Tensorflow docs.

I have installed tensoflow 2.0 with python 3.6.5 and the tensor flow works in python.

Any help would be appreciated.

Regards,
Devika

**Comment by UCDNJJ** [comment]
Hi Devika,

scAlign current does not support Tensorflow 2.0 (just released last week!), could you try installing Tensorflow version 1.15rc2?

**Comment by deevdevil88** [comment]
Hi ,
I installed version 1.9.0  in python and that worked fine with scAlign. However i got an error in the second step , which is the decoding bit when aligning using gene counts. Is that because of the version of the tensor flow as well?

Devika

**Comment by UCDNJJ** [comment]
What was the error you received in the second step? We've had some problems with correct loading of the `purrr` dependency which can cause an error during the decoder stage.
